namespace SFSharp.Abstractions.Interop.RakNet;

public enum EArizonaEx : ushort
{
    BotWorldPedAdd = 50,
    BotWorldPedRemove = 51,
    BotOnfootPedSync = 52,
    BotSendOnfootSync = 53,
    BotSetPedColor = 54,
    BotSetPedFightStyle = 55,
    BotSetPedInvulnerable = 56,
    BotSetPedName = 57,
    BotSetPedSkin = 64,
    BotSetPedWeapon = 65,
    BotSetPedPos = 66,
    BotMovePedToPos = 67,
    BotShootPedAtPos = 68,
    BotApplyPedAnimation = 69,
    BotClearPedAction = 70,
    BotShootPedAtPlayer = 72,
    BotSendDamage = 73,
    BotAttackPlayer = 80,
    BotEnterToVehicle = 81,
    BotPassengerPedSync = 82,
    BotDrivePedSync = 83,
    BotRemoveFromVehicle = 84,
    BotChatBubble = 85,
    BotAttachObject = 86,
    BotDetachObject = 87,
    BotSetPedAngle = 89,
    BotStopAllAction = 96,
    BotShootPedAtPed = 97,
    BotSetAnimationGroup = 98,
    BotAttackPed = 101,
    BotToggleCollision = 102,
    BotAttachSimpleObject = 103,
    BotDetachSimpleObject = 104,
    BotSetHealth = 105,
    BotSetArmour = 112,
    BotSetOnfootSyncRate = 113,
}
