namespace SFSharp.Runtime.Networking.RakNet.Rpc.Parsing;

public static partial class RpcParserCatalog
{
    private static void RegisterIncoming(RpcParserRegistry registry)
    {
        #region incoming (server -> client)
        RegisterIncoming(registry, SampRpcId.SetPlayerName, SampRpc.ParseSetPlayerName);
        RegisterIncoming(registry, SampRpcId.SetPlayerPos, SampRpc.ParseSetPlayerPos);
        RegisterIncoming(registry, SampRpcId.SetPlayerPosFindZ, SampRpc.ParseSetPlayerPosFindZ);
        RegisterIncoming(registry, SampRpcId.SetPlayerHealth, SampRpc.ParseSetPlayerHealth);
        RegisterIncoming(registry, SampRpcId.TogglePlayerControllable, SampRpc.ParseTogglePlayerControllable);
        RegisterIncoming(registry, SampRpcId.PlaySound, SampRpc.ParsePlaySound);
        RegisterIncoming(registry, SampRpcId.SetWorldBounds, SampRpc.ParseSetWorldBounds);
        RegisterIncoming(registry, SampRpcId.GivePlayerMoney, SampRpc.ParseGivePlayerMoney);
        RegisterIncoming(registry, SampRpcId.SetPlayerFacingAngle, SampRpc.ParseSetPlayerFacingAngle);
        RegisterIncoming(registry, SampRpcId.ResetPlayerMoney, SampRpc.ParseResetPlayerMoney);
        RegisterIncoming(registry, SampRpcId.ResetPlayerWeapons, SampRpc.ParseResetPlayerWeapons);
        RegisterIncoming(registry, SampRpcId.GivePlayerWeapon, SampRpc.ParseGivePlayerWeapon);
        RegisterIncoming(registry, SampRpcId.SetVehicleParamsEx, SampRpc.ParseSetVehicleParamsEx);
        RegisterIncoming(registry, SampRpcId.CancelEdit, SampRpc.ParseCancelEdit);
        RegisterIncoming(registry, SampRpcId.SetPlayerTime, SampRpc.ParseSetPlayerTime);
        RegisterIncoming(registry, SampRpcId.ToggleClock, SampRpc.ParseToggleClock);
        RegisterIncoming(registry, SampRpcId.WorldPlayerAdd, SampRpc.ParseWorldPlayerAdd);
        RegisterIncoming(registry, SampRpcId.SetShopName, SampRpc.ParseSetShopName);
        RegisterIncoming(registry, SampRpcId.SetPlayerSkillLevel, SampRpc.ParseSetPlayerSkillLevel);
        RegisterIncoming(registry, SampRpcId.SetPlayerDrunkLevel, SampRpc.ParseSetPlayerDrunkLevel);
        RegisterIncoming(registry, SampRpcId.Create3DTextLabel, SampRpc.ParseCreate3DTextLabel);
        RegisterIncoming(registry, SampRpcId.DisableCheckpoint, SampRpc.ParseDisableCheckpoint);
        RegisterIncoming(registry, SampRpcId.SetRaceCheckpoint, SampRpc.ParseSetRaceCheckpoint);
        RegisterIncoming(registry, SampRpcId.DisableRaceCheckpoint, SampRpc.ParseDisableRaceCheckpoint);
        RegisterIncoming(registry, SampRpcId.GameModeRestart, SampRpc.ParseGameModeRestart);
        RegisterIncoming(registry, SampRpcId.PlayAudioStream, SampRpc.ParsePlayAudioStream);
        RegisterIncoming(registry, SampRpcId.StopAudioStream, SampRpc.ParseStopAudioStream);
        RegisterIncoming(registry, SampRpcId.RemoveBuildingForPlayer, SampRpc.ParseRemoveBuildingForPlayer);
        RegisterIncoming(registry, SampRpcId.CreateObject, SampRpc.ParseCreateObject);
        RegisterIncoming(registry, SampRpcId.SetObjectPos, SampRpc.ParseSetObjectPos);
        RegisterIncoming(registry, SampRpcId.SetObjectRot, SampRpc.ParseSetObjectRot);
        RegisterIncoming(registry, SampRpcId.DestroyObject, SampRpc.ParseDestroyObject);
        RegisterIncoming(registry, SampRpcId.DeathMessage, SampRpc.ParseDeathMessage);
        RegisterIncoming(registry, SampRpcId.SetPlayerMapIcon, SampRpc.ParseSetPlayerMapIcon);
        RegisterIncoming(registry, SampRpcId.RemoveVehicleComponent, SampRpc.ParseRemoveVehicleComponent);
        RegisterIncoming(registry, SampRpcId.Destroy3DTextLabel, SampRpc.ParseDestroy3DTextLabel);
        RegisterIncoming(registry, SampRpcId.ChatBubble, SampRpc.ParseChatBubble);
        RegisterIncoming(registry, SampRpcId.UpdateTime, SampRpc.ParseUpdateTime);
        RegisterIncoming(registry, SampRpcId.ShowDialog, SampRpc.ParseShowDialog);
        RegisterIncoming(registry, SampRpcId.DestroyPickup, SampRpc.ParseDestroyPickup);
        RegisterIncoming(registry, SampRpcId.LinkVehicleToInterior, SampRpc.ParseLinkVehicleToInterior);
        RegisterIncoming(registry, SampRpcId.SetPlayerArmour, SampRpc.ParseSetPlayerArmour);
        RegisterIncoming(registry, SampRpcId.SetPlayerArmedWeapon, SampRpc.ParseSetPlayerArmedWeapon);
        RegisterIncoming(registry, SampRpcId.SetSpawnInfo, SampRpc.ParseSetSpawnInfo);
        RegisterIncoming(registry, SampRpcId.SetPlayerTeam, SampRpc.ParseSetPlayerTeam);
        RegisterIncoming(registry, SampRpcId.PutPlayerInVehicle, SampRpc.ParsePutPlayerInVehicle);
        RegisterIncoming(registry, SampRpcId.RemovePlayerFromVehicle, SampRpc.ParseRemovePlayerFromVehicle);
        RegisterIncoming(registry, SampRpcId.SetPlayerColor, SampRpc.ParseSetPlayerColor);
        RegisterIncoming(registry, SampRpcId.DisplayGameText, SampRpc.ParseDisplayGameText);
        RegisterIncoming(registry, SampRpcId.ForceClassSelection, SampRpc.ParseForceClassSelection);
        RegisterIncoming(registry, SampRpcId.AttachObjectToPlayer, SampRpc.ParseAttachObjectToPlayer);
        RegisterIncoming(registry, SampRpcId.InitMenu, SampRpc.ParseInitMenu);
        RegisterIncoming(registry, SampRpcId.ShowMenu, SampRpc.ParseShowMenu);
        RegisterIncoming(registry, SampRpcId.HideMenu, SampRpc.ParseHideMenu);
        RegisterIncoming(registry, SampRpcId.CreateExplosion, SampRpc.ParseCreateExplosion);
        RegisterIncoming(registry, SampRpcId.ShowPlayerNameTag, SampRpc.ParseShowPlayerNameTag);
        RegisterIncoming(registry, SampRpcId.AttachCameraToObject, SampRpc.ParseAttachCameraToObject);
        RegisterIncoming(registry, SampRpcId.InterpolateCamera, SampRpc.ParseInterpolateCamera);
        RegisterIncoming(registry, SampRpcId.SetObjectMaterial, SampRpc.ParseSetObjectMaterial);
        RegisterIncoming(registry, SampRpcId.GangZoneStopFlash, SampRpc.ParseGangZoneStopFlash);
        RegisterIncoming(registry, SampRpcId.ApplyPlayerAnimation, SampRpc.ParseApplyPlayerAnimation);
        RegisterIncoming(registry, SampRpcId.ClearPlayerAnimations, SampRpc.ParseClearPlayerAnimations);
        RegisterIncoming(registry, SampRpcId.SetPlayerSpecialAction, SampRpc.ParseSetPlayerSpecialAction);
        RegisterIncoming(registry, SampRpcId.SetPlayerFightingStyle, SampRpc.ParseSetPlayerFightingStyle);
        RegisterIncoming(registry, SampRpcId.SetPlayerVelocity, SampRpc.ParseSetPlayerVelocity);
        RegisterIncoming(registry, SampRpcId.SetVehicleVelocity, SampRpc.ParseSetVehicleVelocity);
        RegisterIncoming(registry, SampRpcId.SetPlayerDrunkVisuals, SampRpc.ParseSetPlayerDrunkVisuals);
        RegisterIncoming(registry, SampRpcId.ClientMessage, SampRpc.ParseClientMessage);
        RegisterIncoming(registry, SampRpcId.SetWorldTime, SampRpc.ParseSetWorldTime);
        RegisterIncoming(registry, SampRpcId.CreatePickup, SampRpc.ParseCreatePickup);
        RegisterIncoming(registry, SampRpcId.SetVehicleTires, SampRpc.ParseSetVehicleTires);
        RegisterIncoming(registry, SampRpcId.MoveObject, SampRpc.ParseMoveObject);
        RegisterIncoming(registry, SampRpcId.EnableStuntBonus, SampRpc.ParseEnableStuntBonus);
        RegisterIncoming(registry, SampRpcId.TextDrawSetString, SampRpc.ParseTextDrawSetString);
        RegisterIncoming(registry, SampRpcId.SetCheckpoint, SampRpc.ParseSetCheckpoint);
        RegisterIncoming(registry, SampRpcId.CreateGangZone, SampRpc.ParseCreateGangZone);
        RegisterIncoming(registry, SampRpcId.ToggleWidescreen, SampRpc.ParseToggleWidescreen);
        RegisterIncoming(registry, SampRpcId.PlayCrimeReport, SampRpc.ParsePlayCrimeReport);
        RegisterIncoming(registry, SampRpcId.SetPlayerAttachedObject, SampRpc.ParseSetPlayerAttachedObject);
        RegisterIncoming(registry, SampRpcId.GangZoneDestroy, SampRpc.ParseGangZoneDestroy);
        RegisterIncoming(registry, SampRpcId.GangZoneFlash, SampRpc.ParseGangZoneFlash);
        RegisterIncoming(registry, SampRpcId.StopObject, SampRpc.ParseStopObject);
        RegisterIncoming(registry, SampRpcId.SetNumberPlate, SampRpc.ParseSetNumberPlate);
        RegisterIncoming(registry, SampRpcId.TogglePlayerSpectating, SampRpc.ParseTogglePlayerSpectating);
        RegisterIncoming(registry, SampRpcId.PlayerSpectatePlayer, SampRpc.ParsePlayerSpectatePlayer);
        RegisterIncoming(registry, SampRpcId.PlayerSpectateVehicle, SampRpc.ParsePlayerSpectateVehicle);
        RegisterIncoming(registry, SampRpcId.ConnectionRejected, SampRpc.ParseConnectionRejected);
        RegisterIncoming(registry, SampRpcId.SetPlayerWantedLevel, SampRpc.ParseSetPlayerWantedLevel);
        RegisterIncoming(registry, SampRpcId.ShowTextDraw, SampRpc.ParseShowTextDraw);
        RegisterIncoming(registry, SampRpcId.HideTextDraw, SampRpc.ParseHideTextDraw);
        RegisterIncoming(registry, SampRpcId.ServerJoin, SampRpc.ParseServerJoin);
        RegisterIncoming(registry, SampRpcId.ServerQuit, SampRpc.ParseServerQuit);
        RegisterIncoming(registry, SampRpcId.InitGame, SampRpc.ParseInitGame);
        RegisterIncoming(registry, SampRpcId.RemovePlayerMapIcon, SampRpc.ParseRemovePlayerMapIcon);
        RegisterIncoming(registry, SampRpcId.SetPlayerAmmo, SampRpc.ParseSetPlayerAmmo);
        RegisterIncoming(registry, SampRpcId.SetGravity, SampRpc.ParseSetGravity);
        RegisterIncoming(registry, SampRpcId.SetVehicleHealth, SampRpc.ParseSetVehicleHealth);
        RegisterIncoming(registry, SampRpcId.AttachTrailerToVehicle, SampRpc.ParseAttachTrailerToVehicle);
        RegisterIncoming(registry, SampRpcId.DetachTrailerFromVehicle, SampRpc.ParseDetachTrailerFromVehicle);
        RegisterIncoming(registry, SampRpcId.SetPlayerDrunkHandling, SampRpc.ParseSetPlayerDrunkHandling);
        RegisterIncoming(registry, SampRpcId.SetWeather, SampRpc.ParseSetWeather);
        RegisterIncoming(registry, SampRpcId.SetPlayerSkin, SampRpc.ParseSetPlayerSkin);
        RegisterIncoming(registry, SampRpcId.SetPlayerInterior, SampRpc.ParseSetPlayerInterior);
        RegisterIncoming(registry, SampRpcId.SetPlayerCameraPos, SampRpc.ParseSetPlayerCameraPos);
        RegisterIncoming(registry, SampRpcId.SetPlayerCameraLookAt, SampRpc.ParseSetPlayerCameraLookAt);
        RegisterIncoming(registry, SampRpcId.SetVehiclePos, SampRpc.ParseSetVehiclePos);
        RegisterIncoming(registry, SampRpcId.SetVehicleZAngle, SampRpc.ParseSetVehicleZAngle);
        RegisterIncoming(registry, SampRpcId.SetVehicleParamsForPlayer, SampRpc.ParseSetVehicleParamsForPlayer);
        RegisterIncoming(registry, SampRpcId.SetCameraBehindPlayer, SampRpc.ParseSetCameraBehindPlayer);
        RegisterIncoming(registry, SampRpcId.WorldPlayerRemove, SampRpc.ParseWorldPlayerRemove);
        RegisterIncoming(registry, SampRpcId.WorldVehicleAdd, SampRpc.ParseWorldVehicleAdd);
        RegisterIncoming(registry, SampRpcId.WorldVehicleRemove, SampRpc.ParseWorldVehicleRemove);
        RegisterIncoming(registry, SampRpcId.WorldPlayerDeath, SampRpc.ParseWorldPlayerDeath);
        RegisterIncoming(registry, SampRpcId.DisableVehicleCollisions, SampRpc.ParseDisableVehicleCollisions);
        RegisterIncoming(registry, SampRpcId.SetPlayerObjectNoCameraCol, SampRpc.ParseSetPlayerObjectNoCameraCol);
        RegisterIncoming(registry, SampRpcId.ToggleCameraTarget, SampRpc.ParseToggleCameraTarget);
        RegisterIncoming(registry, SampRpcId.CreateActor, SampRpc.ParseCreateActor);
        RegisterIncoming(registry, SampRpcId.DestroyActor, SampRpc.ParseDestroyActor);
        RegisterIncoming(registry, SampRpcId.ApplyActorAnimation, SampRpc.ParseApplyActorAnimation);
        RegisterIncoming(registry, SampRpcId.ClearActorAnimation, SampRpc.ParseClearActorAnimation);
        RegisterIncoming(registry, SampRpcId.SetActorFacingAngle, SampRpc.ParseSetActorFacingAngle);
        RegisterIncoming(registry, SampRpcId.SetActorPos, SampRpc.ParseSetActorPos);
        RegisterIncoming(registry, SampRpcId.SetActorHealth, SampRpc.ParseSetActorHealth);

        #endregion

        #region bidirectional incoming (server -> client side)
        RegisterIncoming(registry, SampRpcId.Chat, SampRpc.ParseChatMessage);
        RegisterIncoming(registry, SampRpcId.EnterVehicle, SampRpc.ParseEnterVehicleIncoming);
        RegisterIncoming(registry, SampRpcId.ExitVehicle, SampRpc.ParseExitVehicleIncoming);
        RegisterIncoming(registry, SampRpcId.ClickTextDraw, SampRpc.ParseClickTextDrawIncoming);
        RegisterIncoming(registry, SampRpcId.ScmEvent, SampRpc.ParseScmEventIncoming);
        RegisterIncoming(registry, SampRpcId.ClientCheck, SampRpc.ParseClientCheckIncoming);
        RegisterIncoming(registry, SampRpcId.UpdateVehicleDamageStatus, SampRpc.ParseUpdateVehicleDamageStatusIncoming);
        RegisterIncoming(registry, SampRpcId.UpdateScoresAndPings, SampRpc.ParseUpdateScoresAndPings);
        RegisterIncoming(registry, SampRpcId.EditAttachedObject, SampRpc.ParseEditAttachedObjectIncoming);
        RegisterIncoming(registry, SampRpcId.EditObject, SampRpc.ParseEditObjectIncoming);
        RegisterIncoming(registry, SampRpcId.RequestClass, SampRpc.ParseRequestClassResponse);
        RegisterIncoming(registry, SampRpcId.RequestSpawn, SampRpc.ParseRequestSpawnResponse);
        RegisterIncoming(registry, SampRpcId.DestroyWeaponPickup, SampRpc.ParseDestroyWeaponPickup);
        RegisterIncoming(registry, SampRpcId.SelectObject, SampRpc.ParseSelectObject);
        RegisterIncoming(registry, SampRpcId.SrvNetStats, SampRpc.ParseServerNetStatsResponse, name: "ServerNetStatsResponse");
        #endregion
    }
}
