namespace SFSharp;

/// <summary>
/// Known SAMP 0.3.7 RPC identifiers.
/// Incoming = server -> client, Outgoing = client -> server.
/// </summary>
public enum RpcId : byte
{
    // Incoming (server -> client)
    SetPlayerName = 11,
    SetPlayerPos = 12,
    SetPlayerHealth = 14,
    TogglePlayerControllable = 15,
    PlaySound = 16,
    GivePlayerMoney = 18,
    SetPlayerFacingAngle = 19,
    ResetPlayerWeapons = 21,
    GivePlayerWeapon = 22,
    SetVehicleParamsEx = 24,
    SetPlayerTime = 29,
    ToggleClock = 30,
    WorldPlayerAdd = 32,
    SetPlayerSkillLevel = 34,
    Create3DTextLabel = 36,
    DisableCheckpoint = 37,
    SetRaceCheckpoint = 38,
    DisableRaceCheckpoint = 39,
    GameModeRestart = 40,
    PlayAudioStream = 41,
    StopAudioStream = 42,
    RemoveBuildingForPlayer = 43,
    CreateObject = 44,
    SetObjectPos = 45,
    SetObjectRot = 46,
    DestroyObject = 47,
    DeathMessage = 55,
    SetPlayerMapIcon = 56,
    ChatBubble = 59,
    ShowDialog = 61,
    DestroyPickup = 63,
    SetPlayerArmour = 66,
    SetPlayerArmedWeapon = 67,
    SetPlayerTeam = 69,
    PutPlayerInVehicle = 70,
    RemovePlayerFromVehicle = 71,
    SetPlayerColor = 72,
    DisplayGameText = 73,
    ForceClassSelection = 74,
    AttachObjectToPlayer = 75,
    InitMenu = 76,
    ShowMenu = 77,
    HideMenu = 78,
    CreateExplosion = 79,
    ShowPlayerNameTag = 80,
    AttachCameraToObject = 81,
    InterpolateCamera = 82,
    SetObjectMaterial = 84,
    ApplyPlayerAnimation = 86,
    ClearPlayerAnimations = 87,
    SetPlayerSpecialAction = 88,
    SetPlayerFightingStyle = 89,
    SetPlayerVelocity = 90,
    SetVehicleVelocity = 91,
    ClientMessage = 93,
    SetWorldTime = 94,
    CreatePickup = 95,
    MoveObject = 99,
    Chat = 101,
    EnableStuntBonus = 104,
    TextDrawSetString = 105,
    SetCheckpoint = 107,
    CreateGangZone = 108,
    PlayCrimeReport = 112,
    GangZoneDestroy = 120,
    GangZoneFlash = 121,
    StopObject = 122,
    SetNumberPlate = 123,
    TogglePlayerSpectating = 124,
    PlayerSpectatePlayer = 126,
    PlayerSpectateVehicle = 127,
    ConnectionRejected = 130,
    SetPlayerWantedLevel = 133,
    ShowTextDraw = 134,
    HideTextDraw = 135,
    ServerJoin = 137,
    ServerQuit = 138,
    InitGame = 139,
    RemovePlayerMapIcon = 144,
    SetPlayerAmmo = 145,
    SetGravity = 146,
    SetVehicleHealth = 147,
    AttachTrailerToVehicle = 148,
    DetachTrailerFromVehicle = 149,
    SetPlayerInterior = 156,
    SetPlayerCameraPos = 157,
    SetPlayerCameraLookAt = 158,
    SetVehiclePos = 159,
    SetVehicleZAngle = 160,
    SetVehicleParamsForPlayer = 161,
    SetCameraBehindPlayer = 162,
    WorldPlayerRemove = 163,
    WorldVehicleAdd = 164,
    WorldVehicleRemove = 165,
    WorldPlayerDeath = 166,

    // Outgoing (client -> server)
    ClickPlayer = 23,
    ClientJoin = 25,
    EnterVehicle = 26,
    ServerCommand = 50,
    Spawn = 52,
    Death = 53,
    DialogResponse = 62,
    ClickTextDraw = 83,
    EditObject = 117,
    SelectObject = 132,
    UpdatePlayersInfo = 155,
}

/// <summary>
/// Sync packet IDs for non-RPC raw packets.
/// </summary>
public enum PacketId : byte
{
    // RakNet internal
    ConnectionRequestAccepted = 14,
    ConnectionLost = 17,
    ConnectionBanned = 18,
    InvalidPassword = 19,
    ConnectionFailed = 20,
    Rpc = 20,
    Timestamp = 40,
    Authentication = 152,

    // SAMP sync packets (client <-> server)
    IncarData = 200,
    // Arizona RP custom packets (CEF transport layer)
    // packet 220: first byte = sub-id (uint8), rest = payload
    // packet 221: first 2 bytes = sub-id (uint16), rest = payload (bots/extended)
    ArizonaCef = 220,
    ArizonaCefEx = 221,
    RconCommand = 201,
    AimData = 203,
    WeaponsData = 204,
    StatsData = 205,
    BulletData = 206,
    OnfootData = 207,
    MarkersData = 208,
    UnoccupiedData = 209,
    TrailerData = 210,
    PassengerData = 211,
    SpectatorData = 212,
}
