<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj' Or '$(MSBuildProjectName)' == 'NativeHostPack'">
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <BaseIntermediateOutputPath>$(RepositoryRoot)artifacts\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(RepositoryRoot)artifacts\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**</DefaultItemExcludes>
  </PropertyGroup>
  <Import Project="Version.props" Condition="'$(MSBuildProjectName)' == 'SF.Runtime' Or '$(MSBuildProjectName)' == 'SF.Abstractions'" />
</Project>
