<Project>
  <PropertyGroup>
    <SFBaseVersion>3.3.1</SFBaseVersion>
    <Version Condition="'$(Version)' == ''">$(SFBaseVersion)</Version>
    <AssemblyVersion>$(SFBaseVersion).0</AssemblyVersion>
    <FileVersion>$(SFBaseVersion).0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
